#@TYPE: Machine
#@NAME: System Electronics Astrial
#@SOC: i.MX8MP
#@DESCRIPTION: Machine configuration for System Electronics Astrial i.MX 8M Plus board with LPDDR4
#@MAINTAINER: Arduino <info@arduino.cc>

require conf/machine/imx8mp-lpddr4-evk.conf

MACHINEOVERRIDES .= ":imx8mp-lpddr4-evk"

# Override the variables you want to change here
IMX_DEFAULT_BSP = "nxp"
PREFERRED_PROVIDER:virtual/kernel = "linux-imx_6.6"
KBUILD_DEFCONFIG:imx8mp-astrial = ""
KERNEL_DEVICETREE = ""
KERNEL_DEVICETREE:remove:imx8mp-astrial = " freescale/imx8mp-evk-root.dtb"
PREFERRED_PROVIDER:virtual/dtb ?= "arduino-device-tree"

# Include custom device tree for linux kernel
MACHINE_EXTRA_RRECOMMENDS += "arduino-device-tree"

# Add additional out of tree modules
MACHINE_EXTRA_RRECOMMENDS += "kernel-module-nxp-wlan"

# Firmware NXP IW612 chipset
PREFERRED_RPROVIDER_linux-firmware-nxpiw612-sdio = "firmware-nxp-wifi"
MACHINE_EXTRA_RRECOMMENDS += "firmware-nxp-wifi-nxpiw612-sdio firmware-nxp-wifi"

# Hailo PCIE driver
MACHINE_EXTRA_RRECOMMENDS += "kernel-module-hailo-pcie-driver"

# Additional specific packages
MACHINE_EXTRA_RRECOMMENDS += "lmbench"

# Custom wks file
WKS_FILE:mx8mp-nxp-bsp = "imx-imx-boot-singlepart.wks.in"

# @TODO: below seems to be ignored
SERIAL_CONSOLES = "115200;ttymxc0"
