#@TYPE: Machine
#@NAME: Arduino Monza (Qualcomm QCS6490 RB3 Gen 2 Core Kit)
#@SOC: Qualcomm QCS6490
#@DESCRIPTION: Machine configuration for Arduino Monza based on Qualcomm QCS6490 RB3 Gen 2 Core Kit
#@MAINTAINER: Massimo Pennazio <maxipenna@libero.it>

require conf/machine/qcs6490-rb3gen2-core-kit.conf

MACHINEOVERRIDES =. "qcs6490-rb3gen2-core-kit:"

# Override the variables you want to change here
