#@TYPE: Machine
#@NAME: Arduino Monza (VentUNO Q)
#@SOC: Qualcomm IQ-8275
#@DESCRIPTION: Machine configuration for Arduino Monza (VentUNO Q) board based on Qualcomm IQ-8275 SoC and STM32 microcontroller.
#@MAINTAINER: Massimo Pennazio <maxipenna@libero.it>

require conf/machine/ventuno-q.conf

MACHINEOVERRIDES =. "ventuno-q:"

# Override the variables you want to change here
KERNEL_CMDLINE_EXTRA:append = "${@bb.utils.contains('PREFERRED_KERNEL', 'linux-qcom-next-rt', ' isolcpus=2,3 nohz_full=2,3 rcu_nocbs=2,3 irqaffinity=0-1 rcupdate.rcu_expedited=1 cpuidle.off=1', '', d)}"
