# We might have a conf and classes directory, append to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a recipes directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes*/*/*.bb ${LAYERDIR}/recipes*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-arduino-bsp"
BBFILE_PATTERN_meta-arduino-bsp := "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-arduino-bsp = "9"

LAYERDEPENDS_meta-arduino-bsp = "core freescale-layer fsl-bsp-release fsl-sdk-release"
LAYERSERIES_COMPAT_meta-arduino-bsp = "kirkstone nanbield"
