# yaml-language-server: $schema=https://raw.githubusercontent.com/siemens/kas/master/kas/schema-kas.json

header:
  version: 14
  includes:
    - repo: meta-qcom-arduino
      file: ci/base.yml
    - repo: meta-qcom-arduino
      file: ci/qcom-distro.yml

repos:
  meta-qcom-arduino:
    url: https://github.com/qualcomm-linux/meta-qcom-arduino.git
    branch: main

  # meta-arduino is a multi-layer repo; no url = current checkout
  meta-arduino:
    layers:
      meta-arduino-common:
      meta-arduino-qcom:

target:
  - arduino-container-image
