#@TYPE: Machine
#@NAME: Arduino STM32MP25-CM4
#@SOC: STM32MP25
#@DESCRIPTION: Machine configuration for Arduino STM32MP25-CM4 (STM32MP255FAL3, 1x16Gbit DDR4, 16GB eMMC & PAN WL602-B WiFi/BT)
#@MAINTAINER: Massimo Pennazio <m.pennazio@arduino.cc>

require conf/machine/stm32mp25-eval.conf

MACHINEOVERRIDES =. "stm32mp25-eval:"
